---
Name: portfoliowebsite-app
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

# UTF8MB4 has limited support in older MySQL versions.
# Remove this configuration if you experience issues.
---
Name: myproject-database
---
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - pages\CustomSiteConfig
    
SilverStripe\CMS\Model\SiteTree:
    create_default_pages: false

SilverStripe\Assets\File:
  allowed_extensions:
    - vcf
